#!/usr/bin/python
# version 2021/02/08
import argparse
import pandas as pd

def parseArguments():
    # Create argument parser

    parser = argparse.ArgumentParser(description='This script multiplies the connectivity matrix and mu (generated by SIFT)')

    # Positional mandatory arguments
    parser.add_argument("OriMat", help="input Original Matrix file", type=str)
    parser.add_argument("Mu", help="SIFT Mu text file", type=str)
    parser.add_argument("SavePath", help="Output path", type=str)

    # Parse arguments
    args = parser.parse_args()

    return args

def ScaleMu(OriMat, Mu, SavePath):
	#load csv file
	Ori = pd.read_csv(OriMat,header=None).values
	MuV = pd.read_csv(Mu,header=None).values
	Wei = Ori*MuV
	output = pd.DataFrame(Wei).to_csv(SavePath, header=None, index=None)
	# return Wei

# ouput arguments
if __name__ == '__main__':
    # for help function
    args = parseArguments()
    # Run function
    ScaleMu(args.OriMat, args.Mu, args.SavePath)